const visit = (overrides = {}) => ({
  visitDate: overrides.visitDate,
  status: overrides.status || 'completed',
  durationMinutes: overrides.durationMinutes ?? 30,
  repEmail: overrides.repEmail,
  hcpName: overrides.hcpName,
  hcpAreaTag: overrides.hcpAreaTag,
  territoryCode: overrides.territoryCode,
  notes: overrides.notes || null,
});

module.exports = {
  territories: [
    { name: 'North Territory', code: 'N' },
    { name: 'South Territory', code: 'S' },
  ],
  salesReps: [
    { name: 'Admin User', email: 'admin@example.com', territoryCode: 'N' },
    { name: 'Medical Rep', email: 'rep@example.com', territoryCode: 'S' },
  ],
  hcps: [
    {
      name: 'Dr. Julia Navarro',
      areaTag: 'North Clinic - Cardio',
      specialty: 'Cardiology',
      phone: '555-0101',
      email: 'julia.navarro@example.com',
    },
    {
      name: 'Dr. Isaac Stone',
      areaTag: 'Metro Hospital - Neuro',
      specialty: 'Neurosurgery',
      phone: '555-0102',
      email: 'isaac.stone@example.com',
    },
    {
      name: 'Dr. Laila Faris',
      areaTag: 'Southland Medical - Peds',
      specialty: 'Pediatrics',
      phone: '555-0103',
      email: 'laila.faris@example.com',
    },
  ],
  visits: [
    visit({
      visitDate: '2024-05-02',
      repEmail: 'admin@example.com',
      hcpName: 'Dr. Julia Navarro',
      hcpAreaTag: 'North Clinic - Cardio',
      territoryCode: 'N',
      durationMinutes: 45,
      notes: 'Follow-up on cardio device adoption.',
    }),
    visit({
      visitDate: '2024-05-05',
      status: 'scheduled',
      repEmail: 'admin@example.com',
      hcpName: 'Dr. Isaac Stone',
      hcpAreaTag: 'Metro Hospital - Neuro',
      territoryCode: 'N',
      durationMinutes: 30,
      notes: 'Discuss neurosurgery training plan.',
    }),
    visit({
      visitDate: '2024-05-08',
      repEmail: 'rep@example.com',
      hcpName: 'Dr. Laila Faris',
      hcpAreaTag: 'Southland Medical - Peds',
      territoryCode: 'S',
      durationMinutes: 40,
      notes: 'Reviewed pediatric formulary updates.',
    }),
    visit({
      visitDate: '2024-05-11',
      status: 'completed',
      repEmail: 'rep@example.com',
      hcpName: 'Dr. Julia Navarro',
      hcpAreaTag: 'North Clinic - Cardio',
      territoryCode: 'N',
      durationMinutes: 35,
      notes: 'Joint call with admin on device trials.',
    }),
    visit({
      visitDate: '2024-05-12',
      status: 'cancelled',
      repEmail: 'rep@example.com',
      hcpName: 'Dr. Laila Faris',
      hcpAreaTag: 'Southland Medical - Peds',
      territoryCode: 'S',
      durationMinutes: 0,
      notes: 'HCP requested to reschedule.',
    }),
  ],
};
